services:
  - type: web
    name: pong-force-matchmaking
    env: python
    rootDir: pong_force
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn matchmaking_server:app --bind 0.0.0.0:$PORT
    plan: free
